services:
  jobstrackingapp:
    build:
      context: ./frontend/jobs-app
    container_name: jobs-app
    # environment:
    #   - VITE_TEXT_PROCESSOR_API_URL=http://textprocessorapi:8000
    ports:
      - "3000:80"
    depends_on:
      - textprocessorapi
  textprocessorapi:
    build:
      context: ./backend/text-api
    container_name: text-api
    ports:
      - "8000:8000"
  jobsapi:
    build:
      context: ./backend/Jobs
      dockerfile: Jobs.Api/Dockerfile
    container_name: jobs-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - MongoDb__ConnectionString=mongodb://jobs-db:27017
      - MongoDb__DatabaseName=Jobs
      - MongoDb__CollectionName=job_postings
    depends_on:
      - jobsdb
  jobsdb:
    image: mongodb/mongodb-community-server:latest
    container_name: jobs-db
    ports:
      - "27017:27017"
networks:
  default:
    name: jobs-tracking-network